# Shell stuff
brew "zsh"
brew "zsh-syntax-highting"
brew "zsh-completions"

# Development Stuff
brew "vim"
brew "chruby"
brew "ruby-install"
brew 'sqlite'
brew 'jq'

#utilities
brew "wget"
brew "ack"
brew 'awscli'

# Linters
brew "shellcheck"

