# Shell stuff
brew "zsh"
brew "zsh-syntax-highting"
brew "zsh-completions"

# Development Stuff
brew "vim"
brew "chruby"
brew "ruby-install"

#utilities
brew "wget"
brew "ack"

# Linters
brew "shellcheck"
