#! /bin/bash -ex

function mkdir
{
  command mkdir "$1" && cd "$1"
}

function myreadlink() {
  (
  cd "$(find ~/ -name "$1")"        # or  cd ${1%/*}
  echo "$PWD/$(basename "$1")" # or  echo $PWD/${1##*/}
  )
}

# Finds first direction matchern pattern in ${1} and cd's to it
function app() {
    APP_DIRECTORY="$(find "${CODE_HOME}" -name "${1}")"
    APP_DIRECTORY="${APP_DIRECTORY%%$'\n'*}"
    if [[ ${APP_DIRECTORY} == "" ]]; then
        echo "App doesn't exist"
    else
        echo "Switching to app directory: ${APP_DIRECTORY}"
        cd "${APP_DIRECTORY}"
    fi
}

it2prof() { echo -e "\033]50;SetProfile=$1\a" }

function switchtheme() {
    echo "Switching Theme to: ${1}"

    it2prof ${1}
    export COLOR="$1"
}


