#! /bin/bash -ex

function mkdir
{
  command mkdir "$1" && cd "$1"
}

function myreadlink() {
  (
  cd "$(find ~/ -name "$1")"        # or  cd ${1%/*}
  echo "$PWD/$(basename "$1")" # or  echo $PWD/${1##*/}
  )
}


function app() {
    APP_DIRECTORY="$(find "${CODE_HOME}" -name "${1}")"
    if [[ ${APP_DIRECTORY} == "" ]]; then
        echo "App doesn't exist"
    else
        echo "Switching to app directory: ${APP_DIRECTORY}"
        cd "${APP_DIRECTORY}"
    fi
}
